#!/usr/bin/env bash
# This script prints a default string, adding text from '/etc/passwd' in it

IFS=$'\n' read -d '' -r -a lines < /etc/passwd
n=${#lines[@]}
i=0
while [ $i -lt "$n" ]; do
	IFS=':' read -r -a line <<< "${lines[$i]}"
	echo "${lines[$i]}"
	echo "${line[0]}:${line[2]}:${line[5]}"
	((i++))
done
