#!/usr/bin/env bash
# This script prints a default string, adding text from '/etc/passwd' in it

IFS=$'\n' read -d '' -r -a lines < /etc/passwd
n=${#lines[@]}
i=0
while [ $i -lt "$n" ]; do
	IFS=':' read -r -a line <<< "${lines[$i]}"
	echo "The user ${line[0]} is part of the ${line[3]} gang, lives in ${line[5]} and rides ${line[6]}. ${line[2]}'s place is protected by the passcode ${line[1]}, more info about the user here: ${line[4]}"
	((i++))
done
