#!/usr/bin/env bash
# This script prints "Best School" ten times, printing an additional "Hi" after the ninth repetition
i=1
while [ $i -lt 11 ]; do
	if [ $i -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done
	
