#!/usr/bin/env bash
# This script prints ten lines: the fourth is "bad luck", the eighth is "good luck", and the rest are "Best School"

i=1
while [ $i -lt 11 ]; do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
