#!/usr/bin/env bash
# This script prints a string indefinitely and reacts to SIGTERM and SIGINT by printing more text

trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT

echo $$ > /var/run/myscript.pid

function delete_pid_file() {
	rm /var/run/myscript.pid
	exit
}

trap delete_pid_file SIGQUIT SIGTERM

while true; do
	echo "To infinity and beyond"
done


