#!/usr/bin/env bash
# This script prints a string indefinitely and reacts to SIGTERM and SIGINT by printing more text

trap "echo Y U no love me?!" SIGINT

echo $$ > /var/run/myscript.pid

function exit_sigquit() {
	rm /var/run/myscript.pid
	exit 1
}

function exit_sigterm() {
	echo "I hate the kill command"
	exit_sigquit
}

trap exit_sigquit SIGQUIT
trap exit_sigterm SIGTERM

while true; do
	echo "To infinity and beyond"
done


