#!/usr/bin/env bash
# This (init) script manages the script 'manage_my_process', stating the commands to execute when starting, stopping and restarting said program

start() {
	bash manage_my_process &
	pgrep manage_my_process > /var/run/my_process.pid
	echo 'manage_my_process started'
}

stop() {
	sudo pkill -f manage_my_process
	rm -f /var/run/my_process.pid
	echo 'manage_my_process stopped'
}

restart() {	
	sudo pkill -f manage_my_process
	rm -f /var/run/my_process.pid
	bash manage_my_process &
	pgrep manage_my_process > /var/run/my_process.pid
	echo 'manage_my_process restarted'
}

case "$1" in
	start) start ;;
	stop) stop ;;
	restart) restart ;;
	*) echo 'Usage: manage_my_process {start|stop|restart}' ;;
esac
