#!/usr/bin/env bash
# This script creates prints "To infinity and beyond" infinitely, and replies to SIGTERM signals printing "I am invincible!!!"

trap "echo I am invincible!!!" SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done

